version: '2'
services:
  tasklist:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/tasklist
    ports:
      - "6789:6789"
  tasklist:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-static
    volumes:
      - ./tasklist-fe:/tasklist-fe
    ports:
      - "6788:6788"
